import type { Language } from "./site";

const arabic: Record<string, string> = {
  "01 / THE OCCASION": "01 / المناسبة",
  "Your people.": "ناسكن.",
  "Your kind of party.": "والحفلة على ذوقكن.",
  "From the first dance to the last track.": "من أول رقصة لآخر أغنية.",
  "A soundtrack that feels like you.": "موسيقى بتشبهكن.",
  "Weddings": "الأعراس",
  "For the moments you'll remember.": "للحظات اللي بتضلّ بالذاكرة.",
  "And the dance floor you won't want to leave.": "ولأرض رقص ما بدكن تتركوها.",
  "Wedding DJ services": "خدمة DJ للأعراس",
  "Private celebrations": "الحفلات الخاصة",
  "Engagements, birthdays, and just-because nights.": "خطوبات، أعياد ميلاد، وسهرات بلا مناسبة.",
  "Good company deserves good music.": "الجمعة الحلوة بدها موسيقى حلوة.",
  "Private party DJ services": "خدمة DJ للحفلات الخاصة",
  "Made in Lebanon. Ready to travel.": "من لبنان، وجاهز للسفر.",
  "Destination events on request": "مناسبات خارج لبنان حسب الطلب",
  "OPEN FORMAT DJ · LEBANON": "DJ بأسلوب Open Format · لبنان",
  "Your night.": "ليلتكن.",
  "I'm DeeJoe, an open-format DJ in Lebanon. Bringing people together for weddings, private parties, and nights that turn into mornings.": "أنا DeeJoe، دي جي بلبنان بأسلوب Open Format. بجمع الناس على موسيقى عربية وعالمية بالأعراس والحفلات الخاصة، وبسهرات بتكمّل للصبح.",
  "Listen": "اسمعوا",
  "WEDDINGS & PRIVATE EVENTS": "أعراس وحفلات خاصة",
  "Explore DJ services": "تعرّفوا على خدمات الـDJ",
  "DeeJoe at the decks, wearing red sunglasses and headphones": "DeeJoe خلف أجهزة الـDJ بنظارات حمراء وسماعات",
  "FEEL THE CONNECTION.": "عيشوا اللحظة.",
  "BEHIND THE DECKS / 01": "خلف أجهزة الـDJ / 01",
  "Music styles": "أنواع الموسيقى",
  "ARABIC HITS": "أغاني عربية",
  "THE PLACES. THE PEOPLE. THE MUSIC.": "الأماكن. الناس. الموسيقى.",
  "A decade of": "عشر سنين من",
  "bringing nights": "سهرات",
  "to life.": "مليانة حياة.",
  "From Lebanon's lounges and sunset sessions to wedding celebrations. Every room brings a different energy. Every set tells a different story.": "من سهرات اللاونج وجلسات الغروب بلبنان للأعراس. كل مكان إله طاقته، وكل حفلة إلها قصّتها.",
  "DeeJoe mixing music at his DJ controller": "DeeJoe عم يمزج الموسيقى على أجهزة الـDJ",
  "01 / RESIDENCIES & NIGHTLIFE": "01 / إقامات DJ وسهرات",
  "02 / THE CELEBRATIONS": "02 / الأعراس",
  "Behind the decks.": "ورا كل سهرة.",
  "Part of their big day.": "جزء من يومهن الكبير.",
  "And the nights in between.": "وكمان مناسبات جمعتنا.",
  "Private engagements, bachelor parties, and birthdays, plus appearances at many lounges including Gradient, Monte Carlo, and Fuego. Wedding collaborations with event planners include Events And More, It Takes Two Events and Pro Event.": "خطوبات خاصة، bachelor parties وأعياد ميلاد، ومشاركات بأماكن منها Gradient وMonte Carlo وFuego. وبالأعراس، تعاونت مع منظّمي حفلات منهم Events And More وIt Takes Two Events وPro Event.",
  "Explore private celebrations": "تعرّفوا على الحفلات الخاصة",
  "03 / BEHIND THE DECKS": "03 / خلف أجهزة الـDJ",
  "Read the room.": "بحسّ بجوّكن.",
  "Bring it together.": "وبجمع الأذواق.",
  "Explore my experience": "شوفوا خبرتي",
  "DeeJoe in a black T-shirt, photographed in profile": "صورة جانبية لـDeeJoe بتيشيرت أسود",
  "DEEJOE / OPEN FORMAT DJ": "DeeJoe / دي جي Open Format",
  "Different people.": "أذواق مختلفة.",
  "One dance floor.": "وأرض رقص وحدة.",
  "With over a decade in music, I've found that the best sets start with the people in front of you. It's about knowing the room, connecting different tastes, and finding the track that brings everyone together.": "بعد أكتر من عشر سنين بالموسيقى، تعلّمت إنّ الحفلة بتبلّش من الناس اللي قدّامك. بفهم جوّهن، بقرّب بين الأذواق، وبختار الأغنية اللي بتجمع الكل.",
  "From house and techno to Arabic commercial hits, my style crosses genres. I bring that same energy to weddings, intimate celebrations, and nights at venues across Lebanon.": "من House وTechno للأغاني العربية المعروفة، أسلوبي بيجمع أنواع مختلفة. وبحمل هالطاقة للأعراس، الاحتفالات الصغيرة، والسهرات بأماكن عبر لبنان.",
  "years in music": "سنين بالموسيقى",
  "no boundaries, just good music": "أذواق مختلفة، وموسيقى حلوة",
  "A FEW PLACES WE'VE MADE MEMORIES": "أماكن شاركنا فيها لحظات حلوة",
  "Loading Anghami player...": "عم يتحمّل مشغّل Anghami…",
  "02 / PRESS PLAY": "02 / اسمعوا الجوّ",
  "A little taste": "لمحة صغيرة",
  "my sound.": "من موسيقاي.",
  "Arabic favourites. House grooves. Unexpected connections. Get to know the music before we make your night.": "أغاني عربية، إيقاعات House ومزج بيحمل مفاجآت. اسمعوا الموسيقى وتعرّفوا على أسلوبي قبل ما نخطّط لليلتكن.",
  "View my Anghami profile": "زوروا صفحتي على Anghami",
  "The player is taking too long to load. Try reloading it or listen directly on Anghami.": "المشغّل عم يتأخّر بالتحميل. جرّبوا تعيدوا تحميله أو اسمعوا مباشرةً على Anghami.",
  "Player not working?": "المشغّل مش عم يشتغل؟",
  "Reload player": "حمّلوا المشغّل من جديد",
  "Listen directly on Anghami.": "اسمعوا مباشرةً على Anghami.",
  "Loading Google reviews…": "عم تتحمّل آراء العملاء من Google…",
  "FROM THE DANCE FLOOR": "من قلب الحفلة",
  "Their night.": "ليلتهن.",
  "Their words.": "وكلامهن.",
  "Hear from the people who've": "اسمعوا من الناس اللي",
  "shared a celebration with DeeJoe.": "احتفلوا مع DeeJoe.",
  "Google reviews": "آراء العملاء على Google",
  "Read the reviews using the Google link below.": "اقروا الآراء من رابط Google تحت.",
  "The reviews couldn't load. You can still find them on Google.": "ما قدرنا نحمّل الآراء. فيكن تقروها على Google.",
  "Find DeeJoe's reviews on Google": "اقروا آراء العملاء عن DeeJoe على Google",
  "Services": "الخدمات",
  "Music": "الموسيقى",
  "Experience": "الخبرة",
  "Reviews": "آراء العملاء",
  "Aghbe": "أغبه",
  "Jeita": "جعيتا",
  "Jounieh": "جونية",
  "Zaarour": "الزعرور",
  "Nahr El Kalb": "نهر الكلب",
  "Gemmayze": "الجميزة",
  "Mayrouba": "ميروبا",
  "Kaslik": "الكسليك",
  "Beit Chabeb": "بيت شباب",
  "Raouche": "الروشة",
  "Dbayeh": "ضبيه",
  "Faytroun": "فيطرون",
  "Bikfaya": "بكفيا",
  "Klayaat": "القليعات",
  "Zakrit": "زكريت",
  "Fusion Bazaar Night & Sunset Sessions": "ليالي Fusion Bazaar وجلسات الغروب",
  "Fusion Bazaar Night": "ليالي Fusion Bazaar",
  "Commercial House": "Commercial House",
  "Monthly Fusion Bazaar Night": "ليلة Fusion Bazaar شهرية",
  "Bazaar nights, sunset sessions & private parties": "ليالي Bazaar، جلسات غروب وحفلات خاصة",
  "Fusion Bazaar & R&B nights": "ليالي Fusion Bazaar وR&B",
  "Fusion Bazaar nights": "ليالي Fusion Bazaar",
  "Beach Fusion Bazaar & Sunset Sessions": "Fusion Bazaar على البحر وجلسات الغروب",
  "Friday Fusion Bazaar nights": "ليالي Fusion Bazaar يوم الجمعة",
  "Fusion Bazaar & Deep House nights": "ليالي Fusion Bazaar وDeep House",
  "Fusion Bazaar & Deep House Oriental nights": "ليالي Fusion Bazaar وDeep House Oriental",
  "Wedding celebrations": "أعراس",
  "What kind of events do you play?": "بأي مناسبات بتعزف؟",
  "Weddings, engagements, birthdays, bachelor parties, proposals, proms, and private celebrations. Tell me what you're planning and the atmosphere you have in mind.": "أعراس، خطوبات، أعياد ميلاد، bachelor parties، طلبات زواج، حفلات تخرّج ومناسبات خاصة. خبروني شو عم تخطّطوا وشو الجوّ اللي ببالكن.",
  "Can we choose the music?": "فينا نختار الموسيقى؟",
  "Absolutely—your taste is the starting point. Share your favourite genres, must-play songs, and anything you'd rather skip when we discuss your event. My approach is open-format, so there's room for different tastes and generations on the dance floor.": "أكيد، ذوقكن هو البداية. شاركوني الأنواع والأغاني اللي بتحبوها واللي بتفضّلوا ما تنعزف. أسلوبي Open Format، يعني في مساحة لأذواق وأجيال مختلفة بنفس الحفلة.",
  "Do you travel outside Lebanon?": "بتعزف بمناسبات برا لبنان؟",
  "Of course, destination events are considered on request. Share your city, country, and preferred date so we can discuss availability and travel arrangements.": "المناسبات خارج لبنان ممكنة حسب الطلب. ابعتوا المدينة والبلد والتاريخ لنحكي عن التوفّر وترتيبات السفر.",
  "How do I check availability and get a quote?": "كيف منستفسر عن التوفّر والسعر؟",
  "Fill in your event details below and continue on WhatsApp, or choose email. We'll discuss the date, location, and what you have in mind before agreeing on a quote. Sending an enquiry does not reserve a date.": "عبّوا تفاصيل المناسبة وكفّوا على WhatsApp أو اختاروا الإيميل. منحكي عن التاريخ والمكان والجوّ قبل الاتفاق على السعر. إرسال الاستفسار ما بيحجز التاريخ.",
  "What if we haven't picked a date or venue yet?": "وإذا بعد ما حدّدنا التاريخ أو المكان؟",
  "That's fine. Select “Date not decided” and share the city or country you're considering. You can leave the venue blank and tell me more as your plans take shape.": "ما في مشكلة. اختاروا «بعد ما حدّدنا التاريخ» واذكروا المدينة أو البلد اللي ببالكن. فيكن تتركوا خانة المكان فاضية ونكمّل التفاصيل مع تطوّر خطتكن.",
  "Skip to content": "انتقل للمحتوى",
  "DeeJoe home": "DeeJoe — الرئيسية",
  "Main navigation": "التصفّح الرئيسي",
  "Mobile navigation": "التصفّح على الموبايل",
  "Open navigation": "افتح القائمة",
  "Book Your Event": "خلّينا نحكي عن مناسبتكن",
  "Find your soundtrack.": "موسيقى بتشبهكن.",
  "Bringing life to every beat.": "كل إيقاع إله حياة.",
  "Get in touch": "تواصلوا معي",
  "BASED IN LEBANON. MUSIC WITHOUT BORDERS.": "من لبنان. موسيقى بلا حدود.",
  "Let's make it a night.": "ليلة على ذوقكن.",
  "Breadcrumb": "مسار التصفّح",
  "Home": "الرئيسية",
  "WEDDING EXPERIENCE": "خبرة بالأعراس",
  "YOUR OCCASION": "مناسبتكن",
  "Explore my DJ experience": "شوفوا خبرتي وأماكن عزفي",
  "A FEW THINGS TO KNOW": "قبل ما نبلّش",
  "LET'S MAKE IT HAPPEN": "خلّينا نخطّط سوا",
  "A great night": "ليلة حلوة",
  "starts with": "بتبلّش",
  "a hello.": "بمرحبا.",
  "Tell me a little about your celebration.": "خبروني شوي عن مناسبتكن.",
  "We'll take it from there.": "ومنكمّل التفاصيل سوا.",
  "Based in Lebanon.": "موجود بلبنان.",
  "Destination events on request.": "مناسبات خارج لبنان حسب الطلب.",
  "Your event, your way.": "مناسبتكن على ذوقكن.",
  "Required fields are marked with an asterisk (*).": "الخانات المطلوبة عليها نجمة (*).",
  "Your name *": "اسمكن *",
  "What should I call you?": "شو اسمكن؟",
  "What are we celebrating? *": "شو المناسبة؟ *",
  "Choose your event": "اختاروا المناسبة",
  "Event date": "تاريخ المناسبة",
  "Date not decided": "بعد ما حدّدنا التاريخ",
  "City / country *": "المدينة / البلد *",
  "e.g. Beirut, Lebanon": "مثلاً: بيروت، لبنان",
  "Venue": "المكان",
  "(optional)": "(اختياري)",
  "If you have somewhere in mind": "إذا اخترتوا المكان",
  "Anything else?": "تفاصيل إضافية؟",
  "Your music, your people, the vibe you're after…": "الموسيقى اللي بتحبوها، ضيوفكن، والجوّ اللي ببالكن…",
  "Continue on WhatsApp": "كمّلوا على WhatsApp",
  "Opens a message draft. You send it in WhatsApp.": "بيفتح مسوّدة رسالة، وإنتو بتبعتوها على WhatsApp.",
  "Availability and booking are confirmed in conversation.": "التوفّر والحجز بيتأكّدوا بالمحادثة.",
  "Prefer email? Prepare an email instead": "بتفضّلوا الإيميل؟ حضّروا رسالة بدل WhatsApp",
  "Please check the highlighted fields.": "راجعوا الخانات المحدّدة.",
  "Please use the WhatsApp or email links beside this form to discuss your event.": "استعملوا روابط WhatsApp أو الإيميل جنب الاستمارة لنحكي عن مناسبتكن.",
  "Send your draft in WhatsApp to start the conversation. If it didn't open, use the link below. Your date is not reserved yet.": "ابعتوا الرسالة على WhatsApp لنبلّش الحديث. إذا ما فتح التطبيق، استعملوا الرابط تحت. التاريخ بعده مش محجوز.",
  "Send your draft in your email app to start the conversation. If it didn't open, use the link below.": "ابعتوا الرسالة من تطبيق الإيميل لنبلّش الحديث. إذا ما فتح، استعملوا الرابط تحت.",
  "Please enter your name.": "اكتبوا اسمكن.",
  "Please choose your event type.": "اختاروا نوع المناسبة.",
  "Please add a city and country.": "اكتبوا المدينة والبلد.",
  "Choose a valid date, or select ‘Date not decided'.": "اختاروا تاريخ صحيح، أو «بعد ما حدّدنا التاريخ».",
  "Please choose today or a future date.": "اختاروا تاريخ اليوم أو تاريخ لاحق.",
  "Wedding": "عرس",
  "Engagement": "خطوبة",
  "Birthday": "عيد ميلاد",
  "Bachelor party": "Bachelor party",
  "Proposal": "طلب زواج",
  "Prom": "حفلة تخرّج",
  "Private celebration": "حفلة خاصة",
  "Other celebration": "مناسبة تانية"
};

export function uiText(language: Language = "en") {
  return (english: string) => language === "ar" ? arabic[english] ?? english : english;
}
