import type { Language } from "./site";

const arabic: Record<string, string> = {
  "Skip to content": "انتقل للمحتوى",
  "DeeJoe home": "DeeJoe — الرئيسية",
  "Main navigation": "التصفّح الرئيسي",
  "Mobile navigation": "التصفّح على الموبايل",
  "Open navigation": "افتح القائمة",
  "Book Your Event": "خلّينا نحكي عن مناسبتكن",
  "Find your soundtrack.": "موسيقى بتشبهكن.",
  "Bringing life to every beat.": "كل إيقاع إله حياة.",
  "Get in touch": "تواصلوا معي",
  "BASED IN LEBANON. MUSIC WITHOUT BORDERS.": "من لبنان. موسيقى بلا حدود.",
  "Let's make it a night.": "ليلة على ذوقكن.",
  "Breadcrumb": "مسار التصفّح",
  "Home": "الرئيسية",
  "WEDDING EXPERIENCE": "خبرة بالأعراس",
  "YOUR OCCASION": "مناسبتكن",
  "Explore my DJ experience": "شوفوا خبرتي وأماكن عزفي (بالإنكليزي)",
  "A FEW THINGS TO KNOW": "قبل ما نبلّش",
  "LET'S MAKE IT HAPPEN": "خلّينا نخطّط سوا",
  "A great night": "ليلة حلوة",
  "starts with": "بتبلّش",
  "a hello.": "بمرحبا.",
  "Tell me a little about your celebration.": "خبروني شوي عن مناسبتكن.",
  "We'll take it from there.": "ومنكمّل التفاصيل سوا.",
  "Based in Lebanon.": "موجود بلبنان.",
  "Destination events on request.": "مناسبات خارج لبنان حسب الطلب.",
  "Your event, your way.": "مناسبتكن على ذوقكن.",
  "Required fields are marked with an asterisk (*).": "الخانات المطلوبة عليها نجمة (*).",
  "Your name *": "اسمكن *",
  "What should I call you?": "شو اسمكن؟",
  "What are we celebrating? *": "شو المناسبة؟ *",
  "Choose your event": "اختاروا المناسبة",
  "Event date": "تاريخ المناسبة",
  "Date not decided": "بعد ما حدّدنا التاريخ",
  "City / country *": "المدينة / البلد *",
  "e.g. Beirut, Lebanon": "مثلاً: بيروت، لبنان",
  "Venue": "المكان",
  "(optional)": "(اختياري)",
  "If you have somewhere in mind": "إذا اخترتوا المكان",
  "Anything else?": "تفاصيل إضافية؟",
  "Your music, your people, the vibe you're after…": "الموسيقى اللي بتحبوها، ضيوفكن، والجوّ اللي ببالكن…",
  "Continue on WhatsApp": "كمّلوا على WhatsApp",
  "Opens a message draft. You send it in WhatsApp.": "بيفتح مسوّدة رسالة، وإنتو بتبعتوها على WhatsApp.",
  "Availability and booking are confirmed in conversation.": "التوفّر والحجز بيتأكّدوا بالمحادثة.",
  "Prefer email? Prepare an email instead": "بتفضّلوا الإيميل؟ حضّروا رسالة بدل WhatsApp",
  "Please check the highlighted fields.": "راجعوا الخانات المحدّدة.",
  "Please use the WhatsApp or email links beside this form to discuss your event.": "استعملوا روابط WhatsApp أو الإيميل جنب الاستمارة لنحكي عن مناسبتكن.",
  "Send your draft in WhatsApp to start the conversation. If it didn't open, use the link below. Your date is not reserved yet.": "ابعتوا الرسالة على WhatsApp لنبلّش الحديث. إذا ما فتح التطبيق، استعملوا الرابط تحت. التاريخ بعده مش محجوز.",
  "Send your draft in your email app to start the conversation. If it didn't open, use the link below.": "ابعتوا الرسالة من تطبيق الإيميل لنبلّش الحديث. إذا ما فتح، استعملوا الرابط تحت.",
  "Please enter your name.": "اكتبوا اسمكن.",
  "Please choose your event type.": "اختاروا نوع المناسبة.",
  "Please add a city and country.": "اكتبوا المدينة والبلد.",
  "Choose a valid date, or select ‘Date not decided'.": "اختاروا تاريخ صحيح، أو «بعد ما حدّدنا التاريخ».",
  "Please choose today or a future date.": "اختاروا تاريخ اليوم أو تاريخ لاحق.",
  "Wedding": "عرس",
  "Engagement": "خطوبة",
  "Birthday": "عيد ميلاد",
  "Bachelor party": "Bachelor party",
  "Proposal": "طلب زواج",
  "Prom": "حفلة تخرّج",
  "Private celebration": "حفلة خاصة",
  "Other celebration": "مناسبة تانية"
};

export function uiText(language: Language = "en") {
  return (english: string) => language === "ar-LB" ? arabic[english] ?? english : english;
}
